version: "3"
services:
  mongodb:
    image: mongodb
    restart: always
    volumes:
      - /home/vincent/Docker/mongodb/data/db:/data/db

  wikijs:
    image: wikijs
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - /home/vincent/Docker/wikijs/data/:/data/
    depends_on:
      - mongodb
    links:
      - mongodb
    tty: true